<?php

class Universe{
    private $id;
    private $name;
    private $description;

    public function __construct($name){
        $this->id = null;
        $this->name = $name;
        $this->description = null;
    }

    public function toMap(){
        return array(
            "id" => $this->id,
            "name" => $this->name,
            "description" => $this->description
        );
    }

    public static function fromMap($map){
        $universeTmp = new Universe($map["name"]);
        $universeTmp->id = $map["id"];
        $universeTmp->description = $map["description"];

        return $universeTmp;
    }

    public function generateDescription(){
        $this->description = "This is the universe of " . $this->name. " generated by OpenAi";
    }
}